name: Pull Request Reminders
on:
  pull_request:
    branches:
      - master
      - main
jobs:
  review:
    runs-on: ubuntu-latest
    name: Notify Incoming New Pull Request
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: ./
        with:
          SLACK_WEBHOOK_URL: ${{ secrets.PR_SLACK_WEBHOOK_URL }}
        
